### PR TITLE
#9 remove old prometheus.RegisterOrGet and counter.Set

### LINKED ISSUE #9: prometheus.RegisterOrGet is deprecated and breaks make when client is updated to last version
Just tried to update the golang client of prometheus to 0.8.0 and got some errors. Most importantly ``undefined: prometheus.RegisterOrGet``.

```
pushprom$ rm -rf  vendor/src/github.com/prometheus/client_golang/
pushprom$ make dependencies
* go getting all dependencies into vendor/
# pushprom
src/pushprom/delta.go:63: undefined: prometheus.RegisterOrGet
src/pushprom/delta.go:75: undefined: prometheus.RegisterOrGet
src/pushprom/delta.go:86: metric.Set undefined (type prometheus.Counter has no field or method Set)
src/pushprom/delta.go:107: undefined: prometheus.RegisterOrGet
src/pushprom/delta.go:119: undefined: prometheus.RegisterOrGet
src/pushprom/delta.go:155: undefined: prometheus.RegisterOrGet
src/pushprom/delta.go:167: undefined: prometheus.RegisterOrGet
src/pushprom/delta.go:194: undefined: prometheus.RegisterOrGet
src/pushprom/delta.go:206: undefined: prometheus.RegisterOrGet
Makefile:51: recipe for target 'dependencies' failed
make: *** [dependencies] Error 2
```

### PR DESCRIPTION
**Pull request by marcelcorso**
this fixes #9 

by 

 * not using old prometheus.RegisterOrGet 
 * removing the Set method of counters

Removing the set method of counters should also be done in the php libs @samwierema

### CODE REVIEW

File: src/pushprom/delta_test.go [hunk 1]
```diff
@@ -185,7 +179,7 @@ func TestMulti(t *testing.T) {
 		f          func(a, b float64) float64
 		firstValue float64
 	}{
-		{
+		/*{
```
Comment (samwierema) [inline src/pushprom/delta_test.go]: Please remove this code.

**Review by samwierema — APPROVED** [review]
